
[world-preset]
	#Type in the name from the world type which should be selected by default.
	world-preset = "lostcities:lostcity"
	#Type in a valid generation setting for flat world type.
	#Only works if world-type if 'minecraft:flat'.
	flat-settings = "minecraft:bedrock,2*minecraft:dirt,minecraft:grass_block;minecraft:plains"
	#Type in a valid biome for single biome world type.
	#Only works if world-type is 'minecraft:single_biome_surface'.
	single-biome-biome = "minecraft:plains"
	#Disables the preset selection button in the world selection screen.
	disable-button = false
	#The list of world types which should be available in the world selection screen. If empty, all world types are available.
	allowed-world-types = []

