
[general]
	#List of items to force-allow placing in the belt. Takes precedence over blacklist.
	whitelist = ['storagedrawers:drawer_key', 'storagedrawers:quantify_key', 'storagedrawers:shroud_key']
	#List of items to disallow from placing in the belt. (whitelist takes precedence)
	blacklist = []

