
#Dynamic Lights Settings
[Settings]

	[Settings."FPS Counter"]
		"FPS Counter Distance" = 12
		"Display FPS Counter (OFF, SIMPLE, ADVANCED)" = "ADVANCED"

	[Settings.Misc]
		"Render Fog" = true
		#Allowed Values: WINDOWED, BORDERLESS, FULLSCREEN
		"Use Borderless Fullscreen" = "FULLSCREEN"
		"Cloud Height [Raw, Default 256]" = 256
		"Chunk Fade In Quality (OFF, FAST, FANCY)" = "FANCY"
		"Hide JEI Until Searching" = true
		"Enable Extended Server View Distance" = true

	[Settings."True Darkness"]
		#Allowed Values: PITCH_BLACK, REALLY_DARK, DARK, DIM
		"Darkness Setting (PITCH_BLACK, REALLY_DARK, DARK, DIM)" = "DARK"
		"Use True Darkness" = true

		[Settings."True Darkness".Advanced]
			#Range: 0.0 ~ 1.0
			"Minimum Moon Brightness (0->1)" = 0.0
			"Ignore Moon Light" = false
			#Range: 0.0 ~ 1.0
			"Maximum Moon Brightness (0->1)" = 0.25
			"Only Effect Block Lighting" = false

		[Settings."True Darkness"."Dimension Settings"]
			#Range: 0.0 ~ 1.0
			"Dark End Fog Brightness (0->1)" = 0.0
			"Dark Nether?" = false
			"Dark By Default?" = false
			#Range: 0.0 ~ 1.0
			"Dark Nether Fog Brightness (0->1)" = 0.5
			"Dark If No Skylight?" = false
			"Dark Overworld?" = true
			"Dark End?" = false

	[Settings."Entity Distance"]
		"Enable Max Distance Checks" = true
		#List of entities to not cull based on distance.
		#Example: "minecraft:bat"
		"Entity Whitelist" = []
		"(Entity) Max Vertical Render Distance [Raw, Default 32]" = 32
		"(Entity) Max Horizontal Render Distance [Squared, Default 64^2]" = 4096
		"(TileEntity) Max Horizontal Render Distance [Squared, Default 64^2]" = 4096
		"(TileEntity) Max Vertical Render Distance [Raw, Default 32]" = 32

