
#Settings for Singularities.
[Singularities]
	#Should the default recipe for the Ultimate Singularity be generated?
	ultimateSingularityRecipe = false
	#The default amount of items required to create a Singularity.
	#Range: > 1
	defaultMaterialsRequired = 10000
	#Should default recipes be generated for Singularities?
	defaultRecipes = true
	#The default amount of FE required to create a Singularity.
	#Range: > 0
	defaultPowerRequired = 5000000
	#Should the Singularities be enabled?
	enabled = true
	#The item to use as the Catalyst in default Singularity recipes.
	defaultCatalyst = "extendedcrafting:ultimate_catalyst"

#Settings for the Crafting Core.
["Combination Crafting"]
	#How much FE the Crafting Core should hold.
	#Range: > 0
	powerCapacity = 5000000
	#How much FE/t the Crafting Core should use when crafting by default.
	#Range: > 0
	powerRate = 500
	#Should the Crafting Core be enabled?
	enabled = true

#Settings for general things.
[General]
	#Should the Handheld Crafting Table be enabled?
	handheldWorkbench = true

#Settings for the Extended Crafting Tables.
["Table Crafting"]
	#How much FE the Auto Crafting Tables should hold. Higher tiers use double the previous tier.
	#Range: > 0
	autoTablePowerCapacity = 500000
	#How much FE the Auto Crafting Tables should use when auto inserting items.
	#Range: > 0
	autoTableInsertPowerRate = 100
	#Should the Basic Crafting Table inherit vanilla crafting recipes?
	useVanillaRecipes = true
	#Should the Extended Crafting Tables be enabled?
	enabled = true
	#Should the Auto Crafting Tables be enabled?
	autoTablesEnabled = true
	#How much FE the Auto Crafting Tables should use when crafting.
	#Range: > 0
	autoTablePowerRate = 500

#Settings for the Quantum Compressor.
["Quantum Compression"]
	#How much FE the Quantum Compressor should hold.
	#Range: > 0
	powerCapacity = 10000000
	#How much FE/t the Quantum Compressor should use when crafting by default.
	#Range: > 0
	powerRate = 5000
	#Should the Quantum Compressor be enabled?
	enabled = true

#Settings for the Recipe Maker.
["Recipe Maker"]
	#Should the recipe maker add NBT tags when possible?
	useNBT = true
	#Should the recipe maker try to use tags when possible?
	useTags = false
	#Should the Recipe Maker be enabled?
	enabled = true

#Settings for the Flux Crafter.
["Flux Crafting"]
	#How much FE/t the Flux Crafter should pull from each Flux Alternator when crafting by default.
	#Range: > 0
	defaultPowerRate = 400
	#How much FE the Flux Alternator should hold.
	#Range: > 0
	powerCapacity = 80000
	#How much FE the Auto Flux Crafter should hold.
	#Range: > 0
	autoCrafterPowerCapacity = 500000
	#How much FE the Auto Flux Crafter should use when auto inserting items.
	#Range: > 0
	autoCrafterInsertPowerRate = 100
	#Should the Flux Crafter be enabled?
	enabled = true
	#Should the Auto Flux Crafter be enabled?
	autoCrafterEnabled = true

#Settings for the Ender Crafter.
["Ender Crafting"]
	#How long a single Ender Crafter crafting operation should take (in seconds) by default.
	#Range: > 1
	defaultTimeRequired = 60
	#How much FE the Auto Ender Crafter should hold.
	#Range: > 0
	autoCrafterPowerCapacity = 500000
	#How much FE the Auto Ender Crafter should use when auto inserting items.
	#Range: > 0
	autoCrafterInsertPowerRate = 100
	#How much a single Ender Alternator should speed up a craft. This is a percentage of the time required.
	#Range: 0.0 ~ 1.0
	alternatorEffectiveness = 0.01
	#Should the Ender Crafter be enabled?
	enabled = true
	#Should the Auto Ender Crafter be enabled?
	autoCrafterEnabled = true

