
#Anti-Nesting
[antinesting]
	#List of Resource Locations for items to be blocked
	itemBlacklist = []
	#List of Resource Locations for items to be allowed despite matching other blocking checks.
	itemWhitelist = []

