
[Energy]
	#Multiplier for all power generation in the mod
	#Range: 0.001 ~ 1000.0
	generation_multiplier = 1.0
	#Allow solar panel registration: du, elite, advanced, basic
	register_panel = [true, true, true, true]
	#Solar panel power generation: du, elite, advanced, basic
	panel_power = [448, 1792, 112, 28]
	#Allow rtg registration: uranium_rtg, americium_rtg, plutonium_rtg, californium_rtg
	register_rtg = [true, true, true, true]
	#rtg generation: uranium_rtg, americium_rtg, plutonium_rtg, californium_rtg
	rtg_power = [100, 400, 1200, 4000]
	#rtg radiation: uranium_rtg, americium_rtg, plutonium_rtg, californium_rtg
	rtg_radiation = [560, 57800, 200000, 1900000]
	#Steam turbine (one block) base power gen
	steam_turbine_power_gen = 80
	#Decay Generator base power gen
	decay_generator_power_gen = 128

[energy_storage]
	ligtning_rod_charge = 1048576
	#Allow block registration: basic_voltaic_pile, elite_voltaic_pile, advanced_voltaic_pile, basic_lithium_ion_battery, elite_lithium_ion_battery, du_lithium_ion_battery, du_voltaic_pile, advanced_lithium_ion_battery
	energy_block_registration = [true, true, true, true, true, true, true, true]
	#Storage: basic_voltaic_pile, elite_voltaic_pile, advanced_voltaic_pile, basic_lithium_ion_battery, elite_lithium_ion_battery, du_lithium_ion_battery, du_voltaic_pile, advanced_lithium_ion_battery
	energy_block_storage = [1600000, 102400000, 6400000, 32000000, 2048000000, 512000000, 25600000, 128000000]
	lithium_ion_battery_storage = 1048576
	qnp_energy_storage = 2097152
	qnp_energy_per_block = 200

[Misc]
	#Debug logging. Enable in case of issues to collect more data
	debug_logging = false

["GregTech Energy Compatibility"]
	#Tiers: ULV, LV, MV, HV, EV, IV, LuV, ZPM, UV, UHV, UEV, UIV, UXV, OpV, MAX
	#ONLY_FE - Only FE energy system is used
	#ONLY_GTCEU - Only GregTech Energy system is used
	#GTCEU_AND_FE - Both systems are used, but GTCEU is preferred
	#Allowed Values: ONLY_FE, ONLY_GTCEU, GTCEU_AND_FE
	gregtech_energy_compatibility = "GTCEU_AND_FE"
	#This only counts if GTCEU is supported
	fission_reactor_energy_tier = "EV"
	#This only counts if GTCEU is supported
	#Explode machines when input energy is more than max input
	#This doesn't count FE energy input
	gregtech_energy_overcharge_explosions = true
	#This only counts if GTCEU_AND_FE compatibility used
	#Output FE/t will be limited to max GTCEU output
	#Formula: FE/t = voltage * amperage * (EU to FE convertion rate, usually 4)
	limit_fe_output = false
	#This only counts if GTCEU is supported
	turbine_energy_tier = "EV"
	#This only counts if GTCEU is supported
	fusion_reactor_energy_tier = "IV"
	#This only counts if GTCEU is supported
	kugelblitz_energy_tier = "LuV"
	#This only counts if GTCEU is supported
	accelerators_energy_tier = "LuV"
	#This only counts if GTCEU is supported
	processor_energy_tier = "MV"
	#This only counts if GTCEU is supported
	#How many energy upgrades are needed for processor to reach next energy tier
	#Range: 8 ~ 64
	energy_upgrades_for_next_tier = 16

[storage_blocks]
	#Blocks to store items, fluids, etc...
	#Allow container registration: advanced_barrel, basic_barrel, elite_barrel, du_barrel
	container_block_registration = [true, true, true, true]
	#Allow barrel registration: advanced_barrel, basic_barrel, elite_barrel, du_barrel
	barrel_block_registration = [true, true, true, true]
	#Barrel capacity in Buckets: advanced_barrel, basic_barrel, elite_barrel, du_barrel
	barrel_capacity = [512, 128, 8192, 2048]

