
#Settings for reactor fuel
[reactor_fuel]
	#Heat multiplier. Affects to all fuels.
	#Range: 0.01 ~ 100.0
	fuel_heat_multiplier = 1.0
	#Heat multiplier affects on heat/cooling ratio multiplier.
	heat_multiplier = 3.24444444
	#Depletion multiplier. Affects how long fuel lasts.
	#Range: 0.0 ~ 1000.0
	depletion_multiplier = 1.0

#Settings for Fission Reactor
[fission_reactor]
	#Reactor min size.
	#Range: 3 ~ 24
	min_size = 3
	#Reactor max size.
	#Range: 5 ~ 32
	max_size = 13
	#Explosion size if reactor overheats. 4 - TNT size. Set to 0 to disable explosion.
	#Range: 0.0 ~ 20.0
	reactor_explosion_radius = 4.0
	#How much reactor may collect heat before meltdown.
	#Range: 1000.0 ~ 1.0E8
	heat_capacity = 1000000.0
	#Affects how relation of reactor cooling and heating affects to FE generation.
	#Range: 0.01 ~ 20.0
	heat_multiplier = 3.0
	#Limit for heat_multiplier max value.
	#Range: 0.01 ~ 3.0
	heat_multiplier_cap = 3.0
	#Each attachment of moderator to fuel cell will increase fuel FE generation by given percent value.
	#Range: 0.0 ~ 1000.0
	moderator_fe_multiplier = 16.67
	#Each attachment of moderator to fuel cell will increase fuel heat generation by given percent value.
	#Range: 0.0 ~ 1000.0
	moderator_heat_multiplier = 33.34
	#Rate at which steam recipes produced.
	#Range: 0.01 ~ 1000000.0
	boiling_mult = 100.0
	#Affects how much energy reactors produce.
	#Range: 0.01 ~ 1000000.0
	fe_generation_multiplier = 5.0
	#If true, active coolers will be counted in placement rules for other heat sinks.
	active_heatsink_prime = true
	#How much coolant active heat sink will consume per tick.
	#Range: 1 ~ 10000
	active_heatsink_coolant_per_tick = 10
	#If you don't need reactor boiling mode, just disable.
	supports_boiling_mode = true

#Settings for Molten Salt Fission Reactor (MSR)
[msr_reactor]
	#Number of pebbles that can be stored per fuel cell. Determines the maximum pebble capacity.
	#Range: 1 ~ 100
	pebbles_per_fuel_cell = 4

