
#Settings for In situ leaching
[in_situ_leaching]
	#Enable veins generation.
	enable_veins = true
	#Min and max values of blocks per vein.
	#Result amount will be random value in this range.
	blocks_per_vein = [30000, 70000]
	#Veins rarity. Bigger value - less veins.
	#Range: 1 ~ 5000
	veins_rarity = 100
	#All veins will have random ores. It will ignore vein settings
	randomized_ores = false
	#Add new veins to generation for Immersive Engineering.
	add_ie_veins = true
	#Allow to leach veins from Immersive Engineering.
	#To do so, you need to put IE core sample into leacher.
	allow_to_leach_ie_veins = true

["Common settings"]
	#Ticks
	base_time = 240
	#FE per Tick
	#Better use value multiple of 8
	base_power = 128
	#GT EU Amperage
	gteu_amperage = 2
	#GT EU direct support enabled?
	#0 - disabled, 1 - enabled EU and FE, 2 - EU only
	gteu_support = 1
	#Enable explosion on wrong GE EU amperage
	gteu_explode = false
	#Generally used for server optimization. Processors will skip defined amount of ticks then and do nothing.
	#This won't affect recipe production performance
	#Let's say it will skip 2 ticks, and then it will multiply recipe progress by amount if skipped ticks.
	#So it won't do the job each tick. But production will be the same as if it was done each tick.
	#This only works if processor has recipe in work
	#May lead to unknown issues, Please test first
	#Range: 0 ~ 10
	skip_ticks = 0

[rock_crusher]
	register = true
	base_power = 50
	base_time = 200

[decay_hastener]
	register = true
	base_power = 50
	base_time = 200

[irradiator]
	register = true
	base_power = 0
	base_time = 200

[nuclear_furnace]
	register = true
	base_power = 0
	base_time = 200

[extractor]
	register = true
	base_power = 50
	base_time = 200

[electrolyzer]
	register = true
	base_power = 50
	base_time = 200

[pressurizer]
	register = true
	base_power = 50
	base_time = 200

[alloy_smelter]
	register = true
	base_power = 50
	base_time = 200

[melter]
	register = true
	base_power = 50
	base_time = 200

[analyzer]
	register = true
	base_power = 50
	base_time = 200

[ingot_former]
	register = true
	base_power = 50
	base_time = 200

[pump]
	register = true
	base_power = 50
	base_time = 200

[fuel_reprocessor]
	register = true
	base_power = 50
	base_time = 200

[leacher]
	register = true
	base_power = 50
	base_time = 200

[crystallizer]
	register = true
	base_power = 50
	base_time = 200

[assembler]
	register = true
	base_power = 50
	base_time = 200

[steam_turbine]
	register = true
	base_power = 50
	base_time = 200

[supercooler]
	register = true
	base_power = 50
	base_time = 200

[centrifuge]
	register = true
	base_power = 50
	base_time = 200

[chemical_reactor]
	register = true
	base_power = 50
	base_time = 200

[fluid_infuser]
	register = true
	base_power = 50
	base_time = 200

[isotope_separator]
	register = true
	base_power = 50
	base_time = 200

[fluid_enricher]
	register = true
	base_power = 50
	base_time = 200

[gas_scrubber]
	register = true
	base_power = 50
	base_time = 200

[manufactory]
	register = true
	base_power = 50
	base_time = 200

