
#Settings for Turbine
[turbine]
	#Multiblock min size.
	#Range: 5 ~ 25
	min_size = 5
	#Multiblock max size.
	#Range: 5 ~ 25
	max_size = 24
	#Steam flow per blade mB/t
	#Range: 100 ~ 1000000
	blade_flow = 2000
	#Efficiency %: gold, aluminium, copper, magnesium, beryllium, silver
	efficiency = [104.0, 98.0, 110.0, 86.0, 90.0, 112.0]
	#You can define blocks by block_name. So copper_turbine_coil will fall back to nuclearcraft:copper_turbine_coil. Or qualify it with namespace like some_mod:some_block.
	#Or use block tag key. #nuclearcraft:fission_reactor_casing will fall back to blocks with this tag. Do not forget to put #.
	#if you need AND condition, add comma separated values "block1", "block2" means AND condition
	#if you need OR condition, use | separator. "block1|block2" means block1 or block2
	#By default you have rule condition is 'At least 1'. So if you define some block, it will go in the rule as 'at least 1'
	#Validation options: >2 means at least 2 (use any number)
	#-2 means between, it is always 2 (opposite sides)
	#<2 means less than 2 (use any number)
	#=2 means exact 2 (use any number)
	#^3 means 3 blocks in the corner (shared vertex or edge). possible values 2 and 3
	#Default placement rules have all examples
	placement_explanations = ""
	gold = ["turbine_beryllium_coil"]
	aluminium = ["turbine_gold_coil|turbine_magnesium_coil|turbine_beryllium_coil|turbine_gold_coil|turbine_copper_coil"]
	copper = ["turbine_gold_coil"]
	magnesium = ["turbine_bearing"]
	beryllium = ["turbine_magnesium_coil"]
	silver = ["turbine_magnesium_coil", "turbine_gold_coil"]
	#Energy gen per mB of steam
	#Range: 1 ~ 1000000
	energy_gen = 1

