
[Dimension]
	#Register Wasteland Dimension
	wasteland = false

[Biome]
	#Generate Wasteland Biome in Overworld
	wasteland = false

[Villages]
	#Generate Scientist House in Villages
	scientist_house = false
	#Add Wandering Trader trades
	wandering_trader_trades = false

